### ISSUE TITLE
有没有创建定时任务的接口，求解答

### ISSUE THREAD

**Issue by witcombo** [jobxhub/JobX#36]

**Comment by wolfboys** [comment]
你好,感谢关注,目前还没有,预计11月前后有新版发布,会加接口和任务依赖等功能



---原始邮件---
发件人: "Chuan Zhang"<notifications@github.com>
发送时间: 2019年8月8日(星期四) 下午2:45
收件人: "jobxhub/JobX"<JobX@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [jobxhub/JobX] 有没有创建定时任务的接口，求解答 (#36)



Closed #36.
